name: Deploy to neocities

# only run on changes to main. Use main or master depending on whatever your default branch is called.
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # The checkout step copies your repo into the action runner. Important!
    - uses: actions/checkout@v4
    # When the dist_dir is ready, deploy it to neocities
    # Here we deploy the folder named `public`
    - name: Deploy to Neocities
      # You may pin to the exact commit or the version.
      # uses: bcomnes/deploy-to-neocities@08817e531c05b03d934a7edbcd6185ce146cad27
      uses: bcomnes/deploy-to-neocities@v3.0.4
      with:
        # Neocities API key for site to deploy to
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
